WebApplication1/Models/UsuarioModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class UsuarioModel
    {
        [Required]
        public string Nome { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Senha { get; set; }
        [Compare("Senha")]
        public string RelembrarSenha { get; set; }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace WebApplication1.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Logar(string usuario, string senha)
        {
            if(WebSecurity.Login(usuario, senha))
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("Login.Erro", "Usuário ou Senha errado");
                return View("Index");
            }
            
        }

        public ActionResult Deslogar()
        {
            WebSecurity.Logout();
            return RedirectToAction("Index", "Home");
        }
    }
}

WebApplication1/Controllers/MovimentacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.DAO;
using WebApplication1.Entidade;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class MovimentacaoController : Controller
    {
        private readonly UsuarioDAO usuarioDAO;
        private readonly MovimentacaoDAO movimentacaoDAO;
        public MovimentacaoController(UsuarioDAO UsuarioDAO, MovimentacaoDAO MovimentacaoDAO)
        {
            this.usuarioDAO = UsuarioDAO;
            this.movimentacaoDAO = MovimentacaoDAO;
        }
    
        public ActionResult Index()
        {
            return View(movimentacaoDAO.GetList());
        }

        public ActionResult Form()
        {
            ViewBag.Usuarios = usuarioDAO.GetList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar(Movimentacao movimentacao)
        {
            if(ModelState.IsValid)
            {
                movimentacaoDAO.Adicionar(movimentacao);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Form", movimentacao);
            }
        }

    }
}

WebApplication1/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.DAO;
using WebApplication1.Entidade;
using WebApplication1.Models;
using WebMatrix.WebData;

namespace WebApplication1.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly UsuarioDAO usuarioDAO;
        public UsuarioController(UsuarioDAO UsuarioDAO )
        {
            this.usuarioDAO = UsuarioDAO;
        }

        public ActionResult Index()
        {
            var usuarios = usuarioDAO.GetList();
            return View(usuarios);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar(UsuarioModel model)
        {
            if(ModelState.IsValid)
            {
                WebSecurity.CreateUserAndAccount(model.Nome, model.Senha, new { Email = model.Email });
                return RedirectToAction("Index");
            }
            else
            {
                return View("Form", model);
            }
        }

        public ActionResult Form()
        {
            return View();
        }
    }
}

WebApplication1/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@Html.ValidationMessage("Login.Erro")

<form action="/Login/Logar" method="post">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="usuario">Usuário:</label>
        <input type="text" id="usuario" name="usuario" class="form-control" />
    </div>
    <div class="form-group">
        <label for="senha">Senha:</label>
        <input type="password" id="senha" name="senha" class="form-control" />
    </div>
    <br />
    <button class="btn btn-primary" type="submit">Logar</button>
</form>

WebApplication1/Views/Movimentacao/Form.cshtml
@model WebApplication1.Entidade.Movimentacao

@{
    ViewBag.Title = "Formulário";
}
<br />
@Html.ActionLink("Todas as Movimentações", "Index", "Movimentacao", new { @class = "btn btn-primary"})
<br />
<br />

@using(Html.BeginForm("Adicionar", "Movimentacao", FormMethod.Post))
{
    <p>Adicionar Movimentação</p>

    @Html.AntiForgeryToken()

    @Html.LabelFor(m => m.Valor, "Valor:")
    @Html.TextBoxFor(m => m.Valor, new  { @class = "form-control"})
    @Html.ValidationMessageFor(m => m.Valor)

    @Html.LabelFor(m => m.Data, "Data:")
    @Html.TextBoxFor(m => m.Data, new { @class = "form-control"})
    @Html.ValidationMessageFor(m => m.Data)

    @Html.LabelFor(m => m.Tipo, "Tipo:")
    @Html.EnumDropDownListFor( m => m.Tipo, "Selecione o Tipo", new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Tipo)

    @Html.LabelFor(m => m.UsuarioId, "Categoria:")
    @Html.DropDownListFor(m => m.UsuarioId, new SelectList(ViewBag.Usuarios, "Id", "Nome"), new { @class = "form-control"})
    @Html.ValidationMessageFor(m => m.UsuarioId)

    <input type="submit" value="Cadastrar" />
}

WebApplication1/Views/Movimentacao/Index.cshtml
@model  IList<WebApplication1.Entidade.Movimentacao>

@{
    ViewBag.Title = "Movimentação";
}

<br />
@Html.ActionLink("Adicionar", "Form", "Movimentacao", new { @class = "btn btn-primary"})
<br />
<br />

<table class="table table-hover">
    <thead>
        <tr>
            <td>Valor</td>
            <td>Data</td>
            <td>Tipo</td>
            <td>Usuário</td>
        </tr>
    </thead>
    <tbody>
        @foreach(var movimentacao in Model)
        {
            <tr>
                <td>@movimentacao.Valor.ToString("C")</td>
                <td>@movimentacao.Data.ToString("dd/MM/yyyy")</td>
                <td>@movimentacao.Tipo</td>
                <td>@movimentacao.Usuario.Nome</td>
            </tr>
        }
    </tbody>
</table>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
   
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="container-fluid">
        @Html.Partial("_MenuHeader");
        <main class="col-md-8">
            @RenderBody()
        </main>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>

WebApplication1/Views/Shared/_MenuHeader.cshtml
<nav>
    <ul class="nav nav-tabs">
        <li>@Html.ActionLink("Index", "Index", "Home")</li>
        <li>@Html.ActionLink("Movimentação", "Index", "Movimentacao")</li>
        <li>@Html.ActionLink("Usuários", "Index", "Usuario")</li>

        @if (User.Identity.IsAuthenticated)
        {
            <li>@Html.ActionLink("Deslogar", "Deslogar", "Login")</li>
        }
        else
        {
            <li>@Html.ActionLink("Logar", "Index", "Login")</li>
        }
    </ul>
</nav>

WebApplication1/Views/Usuario/Form.cshtml
@model  WebApplication1.Entidade.Usuario

@{
    ViewBag.Title = "Formulário";
}

<br />
@Html.ActionLink("Lista de Usuários", "Index", "Usuario", new { @class = "btn btn-primary" })
<br />
<br />

@using(Html.BeginForm("Adicionar", "Usuario", FormMethod.Post))
{
    @Html.AntiForgeryToken();

    <p>Adicionar Usuário</p>

    @Html.LabelFor(u => u.Nome, "Nome :")
    @Html.TextBoxFor(u => u.Nome, new { @class = "form-control"})
    @Html.ValidationMessageFor(u => u.Nome)

    @Html.LabelFor(u => u.Email, "Email: ")
    @Html.TextAreaFor(u => u.Email, new { @class = "form-control"})
    @Html.ValidationMessageFor(u => u.Email)

    <input type="submit" value="Enviar" />
}

WebApplication1/Views/Usuario/Index.cshtml
@model  IList<WebApplication1.Entidade.Usuario>

@{
    ViewBag.Title = "Movimentação";
}

<br />
@Html.ActionLink("Adicionar", "Form", "Usuario", new {  @class = "btn btn-primary" })
<br />
<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var usuario in Model)
        {
            <tr>
                <td>@usuario.Id</td>
                <td>@usuario.Nome</td>
                <td>@usuario.Email</td>
            </tr>
        }
    </tbody>
</table>